### ISSUE TITLE
Error after upgrading to V14

### ISSUE THREAD

**Issue by Mahuro** [vertcoin-project/vertcoin-core#77]
Hi there,

My setup:

ccminer 8.21-KlausT (64bit) for nVidia GPUs

p2pool (version 51b1663-dirty)

Vertcoin Core version v0.13.3.0-1cd3351 (64-bit) <= UPDATED TO v.14 !!

I hope somebody can help me. I updated to the recent v.14 , but since then I get this error on my cc miner

[2018-12-29 19:09:29] Error: no answer to Stratum authorization request
[2018-12-29 19:09:29] ...retry after 20 seconds

an endless loop .... are there any further adjustmens to be done? I gueess we are still using the lyra2v2 algo in ccminer?

Thanks !

Mauricio.

**Comment by Mahuro** [comment]
update:

Stratum connect failed: Failed to connect to 127.0.0.1 port 9171: Connection refused
[2018-12-29 19:21:05] ...retry after 20 seconds

mi P2p00l refuses connection of my ccminer, since updating to Vertcoin core v.14 !

Help !!

**Comment by metalicjames** [comment]
What are the log messages from P2Pool?

**Comment by nerdy2188** [comment]
I updated wallet and OCM
Error in DeferredResource handler:
Traceback (most recent call last):
  File "p2pool\util\deferred_resource.pyc", line 24, in render

  File "twisted\internet\defer.pyc", line 150, in maybeDeferred

  File "twisted\web\resource.pyc", line 250, in render

  File "twisted\internet\defer.pyc", line 1447, in unwindGenerator

--- <exception caught here> ---
  File "twisted\internet\defer.pyc", line 1301, in _inlineCallbacks

  File "p2pool\web.pyc", line 198, in render_GET

  File "p2pool\web.pyc", line 203, in <lambda>

  File "p2pool\data.pyc", line 631, in get_pool_attempts_per_second

exceptions.AssertionError:






   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.SeekCore(Int64 offset, SeekOrigin origin)
   at System.IO.FileStream.Seek(Int64 offset, SeekOrigin origin)
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   --- End of inner exception stack trace ---
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   at System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen)
   at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
   at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding)
   at VertcoinOneClickMiner.Main.Client_MinerDownloadCompleted(Object sender, AsyncCompletedEventArgs e)
- 2018-02-28T21:13:34.6314938Z, SaveSettingsJSON: SaveSettings: OK.
- 2018-02-28T21:13:34.6471283Z, Client_MinerDownloadCompleted: MinerDownloadCompleted: OK.
- 2018-02-28T21:13:36.1472592Z, SaveSettingsJSON: SaveSettings: OK.
- 2018-02-28T21:13:40.0072301Z, SaveSettingsJSON: SaveSettings: OK.
- 2018-02-28T21:13:42.5237930Z, Download_Miner: Downloaded OK.
- 2018-02-28T21:13:43.6017925Z, Client_MinerDownloadCompleted: System.IO.InvalidDataException: Central Directory corrupt. ---> System.IO.IOException: An attempt was made to move the file pointer before the beginning of the file.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.SeekCore(Int64 offset, SeekOrigin origin)
   at System.IO.FileStream.Seek(Int64 offset, SeekOrigin origin)
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   --- End of inner exception stack trace ---
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   at System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen)
   at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
   at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding)
   at VertcoinOneClickMiner.Main.Client_MinerDownloadCompleted(Object sender, AsyncCompletedEventArgs e)
- 2018-02-28T21:13:43.6017925Z, SaveSettingsJSON: SaveSettings: OK.
- 2018-02-28T21:13:43.6017925Z, Client_MinerDownloadCompleted: MinerDownloadCompleted: OK.
- 2018-02-28T21:13:48.8464554Z, SaveSettingsJSON: SaveSettings: OK.
- 2018-03-11T10:59:27.2243885Z, LoadSettingsJSON: LoadSettings: OK.
- 2018-03-11T10:59:27.3216474Z, Form1_Load: Loaded: OK, V:1.1.8.0
- 2018-03-11T10:59:38.2667468Z, SaveSettingsJSON: SaveSettings: OK.
- 2018-03-11T10:59:42.5030113Z, settings_Load: Loaded: OK.
- 2018-03-11T11:00:17.6213790Z, SaveSettingsJSON: SaveSettings: OK.
- 2018-03-11T11:00:17.6283983Z, Settings_Closing: Closed: OK.
- 2018-03-11T11:00:28.8325922Z, Kill_P2Pool: Kill_P2Pool: OK.
- 2018-03-11T11:00:40.6339691Z, SaveSettingsJSON: SaveSettings: OK.
- 2018-03-11T11:00:46.4043108Z, Download_P2Pool: Downloaded OK.
- 2018-03-11T11:00:58.9135692Z, Download_P2PoolInterface: Downloaded OK.
- 2018-03-11T11:00:58.9175810Z, Client_P2PoolDownloadCompleted: P2PoolDownloadCompleted: OK.
- 2018-03-11T11:01:08.9803357Z, Generate_RPC_Settings: Generate_RPC_Settings: OK.
- 2018-03-11T11:01:08.9883553Z, Check_RPC_Settings: Main() Check_RPC_Settings: OK.
- 2018-03-11T11:01:08.9923662Z, Client_P2PoolInterfaceDownloadCompleted: P2PoolInterfaceDownloadCompleted: OK.
- 2018-03-11T11:01:09.0043994Z, Update_P2Pool_Config: Update_P2Pool_Config: OK.
- 2018-03-11T11:01:09.0134225Z, SaveSettingsJSON: SaveSettings: OK.
- 2018-03-11T11:01:09.0184353Z, SaveSettingsJSON: SaveSettings: OK.
- 2018-03-11T11:01:09.2721108Z, UPnP: SET OK. Ports set: 9181,9347
- 2018-03-11T11:01:09.3302649Z, Start_P2Pool: Start_P2Pool: OK.
- 2018-03-11T11:01:09.8285892Z, Check_RPC_Settings: Main() Check_RPC_Settings: OK.
- 2018-03-11T11:01:09.8336040Z, Update_P2Pool_Config: Update_P2Pool_Config: OK.
- 2018-03-11T11:01:09.8396203Z, SaveSettingsJSON: SaveSettings: OK.
- 2018-03-11T11:01:09.8977740Z, UPnP: SET OK. Ports set: 9181,9347
- 2018-03-11T11:01:09.9027865Z, Start_P2Pool: Start_P2Pool: OK.
- 2018-03-11T11:01:52.4986681Z, Kill_P2Pool: Kill_P2Pool: OK.
- 2018-03-11T11:01:53.8903398Z, Check_RPC_Settings: Main() Check_RPC_Settings: OK.
- 2018-03-11T11:01:53.8943530Z, Update_P2Pool_Config: Update_P2Pool_Config: OK.
- 2018-03-11T11:01:53.8997077Z, SaveSettingsJSON: SaveSettings: OK.
- 2018-03-11T11:01:53.9541426Z, UPnP: SET OK. Ports set: 9181,9347
- 2018-03-11T11:01:53.9641693Z, Start_P2Pool: Start_P2Pool: OK.
- 2018-03-11T11:02:29.7328371Z, Kill_P2Pool: Kill_P2Pool: OK.
- 2018-03-11T11:02:31.7932832Z, Check_RPC_Settings: Main() Check_RPC_Settings: OK.
- 2018-03-11T11:02:31.7982979Z, Update_P2Pool_Config: Update_P2Pool_Config: OK.
- 2018-03-11T11:02:31.8032697Z, SaveSettingsJSON: SaveSettings: OK.
- 2018-03-11T11:02:31.8555184Z, UPnP: SET OK. Ports set: 9181,9347
- 2018-03-11T11:02:31.8725427Z, Kill_P2Pool: Kill_P2Pool: OK.
- 2018-03-11T11:02:31.8765533Z, Start_P2Pool: Start_P2Pool: OK.
- 2018-03-11T11:02:32.3301898Z, Check_RPC_Settings: Main() Check_RPC_Settings: OK.
- 2018-03-11T11:02:32.3352310Z, Update_P2Pool_Config: Update_P2Pool_Config: OK.
- 2018-03-11T11:02:32.3382103Z, SaveSettingsJSON: SaveSettings: OK.
- 2018-03-11T11:02:32.3911192Z, UPnP: SET OK. Ports set: 9181,9347
- 2018-03-11T11:02:32.3941553Z, Start_P2Pool: Start_P2Pool: OK.
- 2018-03-11T11:02:42.8362180Z, Kill_P2Pool: Kill_P2Pool: OK.
- 2018-03-11T11:02:46.5556815Z, settings_Load: Loaded: OK.
- 2018-03-11T11:02:51.4672435Z, SaveSettingsJSON: SaveSettings: OK.
- 2018-03-11T11:02:51.4692713Z, Settings_Closing: Closed: OK.
- 2018-03-11T11:02:53.0174022Z, Main_Closing: 
Log

**Comment by metalicjames** [comment]
This is an OCM problem. Original poster never responded.
